In [2]:
%pip install numpy

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.3/5.3 MB 52.1 MB/s  0:00:00
Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np

In [7]:
x = [1,2,3,4]
x = np.array(x)

print(type(x))

y = x.copy()
y[3] = 99

print (x) 
print (y)

<class 'numpy.ndarray'>
[1 2 3 4]
[ 1  2  3 99]


In [ ]:
A = np.array ([[1,2,3],
               [4,5,6],
               [6,7,8]])

row1 = A[0,:]
col2 = A[:, 1]
something = A[0:2, 2:0]

print("1st row" , row1)
print("2nd col" , col2)
print()

1st row
2nd col


In [ ]:
z = np.arange(1,6)
print (z.shape , z.T , z.T.shape)


A = np.array ([[1,2,3],
               [4,5,6]])

print(A, A.shape)

print(z.T , A.T.shape)


z = z[:, None] // z.reahape[, 5]



(5,) [1 2 3 4 5] (5,)
[[1 2 3]
 [4 5 6]] (2, 3)
[1 2 3 4 5] (3, 2)
